### ISSUE TITLE
MC not working :(

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#37]
![image](https://user-images.githubusercontent.com/9310914/68521799-96ef1680-0272-11ea-90b6-55801c298849.png)

**Comment by Vitae666** [comment]
errr....or MC in game isn't working....
![image](https://user-images.githubusercontent.com/9310914/68521822-e3d2ed00-0272-11ea-9f75-063cc49ee7fe.png)

For that matter...I think Lucky Followers was skipped this cycle as well by the game. I went from Dungeon to Keys.

**Comment by Vitae666** [comment]
UGH...FML...again with the no activation without clicking at least 1 card. I got smart and clicked the last card this time as a test.
![image](https://user-images.githubusercontent.com/9310914/68521945-e255f480-0273-11ea-84c0-74e873c19ddc.png)

Tho, regarding LF. Apparently it happened. But I 100% checked the logs and there was nothing in there at all. But I still feel like I went from Dung to Keys straight away. :-/

**Comment by Vitae666** [comment]
Had the same issue today. MC said it was not active today. Went in game, it was and I hadn't made a pick yet. Did the bottom right and it woke up and started working.

**Comment by Vitae666** [comment]
Well...hell...today it did it on it's own. dah hell?

**Comment by MatthieuBonne** [comment]
Did you update the exe ? This should have been fixed weeks ago... :\

**Comment by Vitae666** [comment]
When I posted 13 days ago, I was on 4.5.0.5. Same version as 5 days ago when it worked. That version came out 16 days ago.
Don't know why it's an on/off thing.
Going to get the new version now.

**Comment by Vitae666** [comment]
BTW, still having the issue. This MC round I had to click a card to get CQA to start.

**Comment by MatthieuBonne** [comment]
I can't find an explanation...
Do you restart CQA often ? Or let it run all week ?

**Comment by Vitae666** [comment]
If there's no rare occurrence of a crash from CQA, then I just let it run.

**Comment by Vitae666** [comment]
> I can't find an explanation...
> Do you restart CQA often ? Or let it run all week ?

Came home to "PG match cards: not active today"
Disabled/Enabled it. Disabled/Enabled Events. Quit/Restarted CQA
Still "PG match cards: not active today"
Pick a card. Voila!  "CQA is playing, please wait" :-/

**Comment by Vitae666** [comment]
For what it's worth, I still rarely have this run on it's own. 1 outta 4 if I'm lucky.
I just keep going into the game and flipping a card to get it started.

WHOOPS! Didn't mean to close it. LOL

**Comment by Vitae666** [comment]
Might as well close this. 
It's still hit or miss. I'll have 2 no-runs, then a run, then 3 no-runs, then 2 runs, then a no-run.
No idea why, but I'm used to it by now and if MC says it's not active on it's day, I just go check and see.
