### ISSUE TITLE
Auction House Levels don't update until you login to the game

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQAutomater#45]
Had CQA up and running the other day (before the Auction End timer fix) and won Marauder Magnus, but the level didn't update. Figured it might be tied to the End timer issue.
After I updated to the current version, I wanted to get Tetra and won. I let AH refresh about 30 times (I was watching a movie) and it always showed that I had 0 levels. I logged into the game, and suddenly it updated to 1 when AH next refreshed.

**Comment by Vitae666** [comment]
![image](https://user-images.githubusercontent.com/9310914/76013625-3ef5b300-5ee6-11ea-8758-a450e3e6357b.png)
Limited to buying 1, but because the count won't update if the game isn't up, I got 2. Not a huge deal cause it was cheap, but just showing what I mean :)

**Comment by Vitae666** [comment]
Oh, meant to add that the Current UM won't update either. But that might still be due to the fact that the game won't update your UM for a minute after you log in.
CQA and game both had 900-something. Then they updated to 3995.
CQA used to pull the correct # until these few recent builds. Don't know what happened, but it was, I'm almost positive, before the Auction timer fix.

**Comment by Vitae666** [comment]
Wanted to check if this was still the case so I could close it.
Haven't had auctions set up for a while because I was wanting to get some of those Hero Shop ones and save up UM for them.
As a test, I won Gurth who I already had 43 levels in and after 20 refreshes AH still displayed 43 :cry: 
Went into the game, checked Gurth and it still said 43. Did an "Update Currencies" and it updated to 44 in game and after a refresh in CQA's AH, it updated to 44 as well.
So, it's still happening :tired_face: 

Would it be possible for AH to, when a Hero you have set gets the timer reset due to an AH win, _yours or someone elses_, for it to send an "Update Currencies"?
I know after you click it, it won't let you click again for 1 minute, so that might screw up when you have multiple heroes and one of the timer happens to fall with in that 1 min window. Maybe a delay counter of some sort? Dunno.
But at least it would, in theory, correctly set the Hero levels and Current UM.
Note I'm saying on a win and not when the timer runs down because that nearly always goes negative and then resets to 1min. Talking about how when there's a win, the Current Price, Bidder, and Ends in go blank. And even then, I think it would be have to be after the data is repopulated.

**Comment by MatthieuBonne** [comment]
I'll change updates in next commit. :)

**Comment by Vitae666** [comment]
Actually..hell....maybe on the 1 min timer would make more sense?
Dunno if the counting down to the negatives would make a diff.
I see a few lines with "updatecurr" and I swear, I think one of them is for this exact purpose. But dunno. It could be something completely different than the clicking of Update Currencies. No clue :)

**Comment by Vitae666** [comment]
It's been over 3hrs since I placed a bid and my UM on hand hasn't updated...
![image](https://user-images.githubusercontent.com/9310914/83715312-14a5b580-a5fb-11ea-97af-80115df3cebb.png)

Log into the game. Click Update Currencies...
![image](https://user-images.githubusercontent.com/9310914/83715576-b3321680-a5fb-11ea-8231-63fc70bb5b00.png)

**Comment by Vitae666** [comment]
Still an issue :sob: 
![image](https://user-images.githubusercontent.com/9310914/92957474-95fcb780-f436-11ea-94ec-99415a93d0af.png)
![image](https://user-images.githubusercontent.com/9310914/92957564-baf12a80-f436-11ea-8191-e7a845a9a2e4.png)
![image](https://user-images.githubusercontent.com/9310914/92957587-c80e1980-f436-11ea-90cc-f02ee286aa18.png)

So's the AH UM not updating, btw :)

**Comment by MatthieuBonne** [comment]
Hopefully fixed in next commit !

**Comment by Vitae666** [comment]
Semi-good news:
As far as I can tell, from just 1 AH purchase, the UM is updating. BUUUUT Hero levels aren't. It was almost 15hrs ago, so with a Refresh every minute, there's no way internet speed is related :)

![image](https://user-images.githubusercontent.com/9310914/93926105-19df5b00-fce5-11ea-8e1b-573d4b0c86f5.png)
![image](https://user-images.githubusercontent.com/9310914/93926155-295ea400-fce5-11ea-8e0f-b7ce56ac0774.png)
![image](https://user-images.githubusercontent.com/9310914/93926489-8eb29500-fce5-11ea-91a0-c6bed63f59dc.png)

**Comment by Vitae666** [comment]
Ok, still happening. 2nd test run.

9/25/2020 7:27:45 PM	Bid on hero Neil for: 5500UM.
![image](https://user-images.githubusercontent.com/9310914/94331342-a9ad2f80-ff99-11ea-9926-2ca656f0685f.png)

**Comment by Vitae666** [comment]
AARGH....Hate to say it, but today, I woke up, to 2111UM from a Spike auction that was well into the next purchase round with 66 still as the level in CQA.
I went into game, to see if I had won which based on the UM updating correctly previously, I was sure I had.....yeah...I hadn't. 
Went to Hero Mgr, clicked Update and it updated to 11081 :(
Don't know why. It was updating correctly previously.
